name: Allure Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET    
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore NuGet packages
      run: dotnet restore   
      
    - name: Build Solution   
      run: dotnet build --configuration Release
      
    - name: Ensure browsers are installed
      run: pwsh bin/Release/net8.0/playwright.ps1 install --with-deps
      
    - name: Run Playwright tests
      run: |
        dotnet test --configuration Release

    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history

    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history
        publish_branch: gh-pages

    - name: Upload Allure Results for Debugging
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
